### ISSUE TITLE
Helm install fails

### ISSUE THREAD

**Issue by petersonnek** [cloudworkz/kafka-minion-helm-chart#1]
Incorrect check in `sasl-secret.yaml` based on default values.yaml.

Current check
`{{- if and (.Values.sasl.enabled) (not .Values.sasl.existingCredentialsSecret) -}}`

should be

`{{- if and (.Values.kafka.sasl.enabled) (not .Values.kafka.sasl.existingCredentialsSecret) -}}`

**Comment by weeco** [comment]
@petersonnek Thanks for creating the issue and immediately submitting the according PR!

I haven't had much time yet to work on the Helm chart, therefore you unfortunately must expect some more issues and missing features (such as the TLS support). I'll try to work on it during the next days though!
