### ISSUE TITLE
Using only TLS cert without username/password

### ISSUE THREAD

**Issue by gurukashyap** [cloudworkz/kafka-minion-helm-chart#11]
I am trying to use minions with TLS enabled without key & password. I see below error message. Looks like we cannot just provide key. Please let me know.

 helm install kafka-minion kafka-minion/kafka-minion --set kafka.tls.enabled=true --set kafka.brokers="{brokers list}" --set kafka.tls.certificates.ca="$(cat ./kafka.client.truststore.jks)"

` kafka-minion/templates/tls-secret.yaml:17:51: executing "kafka-minion/templates/tls-secret.yaml" at <b64enc>: invalid value; expected string`

**Comment by weeco** [comment]
Have you tried passing an empty string?
