### ISSUE TITLE
containerPort does not map to telemetry port value in deployment template

### ISSUE THREAD

**Issue by joan-s-molas** [cloudworkz/kafka-minion-helm-chart#3]
In the deployment template, the http containerPort does not match the telemetry port in the value file - it's just statically set to 80, which causes the probes to endlessly fail:

```          ports:
            - name: http
              containerPort: 80
              protocol: TCP
```
I think it should be

```          ports:
            - name: http
              containerPort: {{ .Values.telemetry.port }}
              protocol: TCP
```

**Comment by weeco** [comment]
Fixed by https://github.com/cloudworkz/kafka-minion-helm-chart/pull/4 but not yet packaged.

Thanks for submitting the issue + PR 🔥

**Comment by weeco** [comment]
Packageed and pushed
