### ISSUE TITLE
Feature: TLS support

### ISSUE THREAD

**Issue by cdenneen** [cloudworkz/kafka-minion-helm-chart#5]
values.yml shows tls hash but this doesn't translate to configuration

**Comment by weeco** [comment]
Yes tls support is yet to be added. I'd like to support both tls certs using existent secrets as well as specifying the contents via values.

Do you want to go ahead and submit a pr for that?

**Comment by cdenneen** [comment]
@weeco I'm currently using the ENV variables to do this but saw the `values.yml` and realized how confusing this might actually be for someone so wanted to make sure there was an open Issue just in case someone tried to modify the value and it was wondering why it wasn't working. If I get time I can try to do this but for right now this was more as informational placeholder to help people.

**Comment by weeco** [comment]
Alright got it, thank you for submitting the issue

**Comment by weeco** [comment]
Hey @cdenneen I pushed TLS/SASL support along with the missing documentation. Do you mind giving this configuration a try to ensure it's working as intended? Unfortunately I don't have a chance to test this right now.
