### ISSUE TITLE
ServiceMonitor is broken

### ISSUE THREAD

**Issue by rjanovski** [cloudworkz/kafka-minion-helm-chart#7]
the chart-generated servicemonitor has a selection label of:
```
  Selector:
    Match Labels:
      App:  kafka-minion
```

but the actual service generated by the chart has labels:
```
Labels:            app.kubernetes.io/instance=km
                   app.kubernetes.io/managed-by=Tiller
                   app.kubernetes.io/name=kafka-minion
```

so no match, and no target, and no discovery.

My workaround:
manually creating the service monitor with:
```
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-minion
```

**Comment by weeco** [comment]
Fixed by https://github.com/cloudworkz/kafka-minion-helm-chart/pull/8
Thank you :)
